# Generated by Django 2.0.6 on 2018-07-03 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('fat', models.DecimalField(decimal_places=1, max_digits=10)),
                ('carbs', models.DecimalField(decimal_places=1, max_digits=10)),
                ('cholesterol', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.Recipe')),
            ],
        ),
    ]
