# Generated by Django 2.0.6 on 2018-07-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0002_nutrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='protein',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
