# Generated by Django 2.0.6 on 2018-07-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0003_nutrition_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
